### ISSUE TITLE
What errors

### ISSUE THREAD

**Issue by lehoangnam14** [J2TeaM/J2TeaM-Security#11]
![image](https://cloud.githubusercontent.com/assets/7042462/20373835/2d927e94-aca7-11e6-863e-86c39e789c27.png)

**Comment by J2TeaM** [comment]
Hi Nam!

Bạn có thể cho mình biết bạn thấy lỗi này khi đang xem URL nào không?

**Comment by lehoangnam14** [comment]
Trang nào cũng thấy lỗi đó cả mà :)

**Comment by J2TeaM** [comment]
Mình cũng đang trên Facebook đây. Mở console thì thấy lỗi từ các extension chặn quảng cáo nhưng không thấy lỗi nào như trong hình của bạn (dù nãy giờ đã chuyển qua lại khá nhiều trang).
