### ISSUE TITLE
Thêm Addon cho firefox :V

### ISSUE THREAD

**Issue by Qynklee** [J2TeaM/J2TeaM-Security#12]
như tiêu đề em đã viết, thực sự em rất thích j2team security mong anh sớm phát triển thêm add cho cả firefox nữa ạ ^^
Thank anh nhiều !

**Comment by J2TeaM** [comment]
Khi nào bên Chrome đạt 10.000 người dùng thì anh bắt đầu phát triển phiên bản cho Firefox nhé!

http://code.junookyo.xyz/j2team-security-for-firefox/index.php
