### ISSUE TITLE
Lỗi Tính Thời gian online

### ISSUE THREAD

**Issue by NguyenTan2405** [J2TeaM/J2TeaM-Security#13]
chào bạn. sao khi mình đăng xuất ra đăng nhập tải khoản  khác thì thời gian không reset lại nhỉ?

**Comment by Qynklee** [comment]
Theo mình đó là hoàn toàn đúng thôi bạn vì nó tính thời gian truy cập FB chứ k tính nhiều acc đâu, mình thấy như thế phù hợp mà vì mình có nhiều acc fb :V

**Comment by J2TeaM** [comment]
Vẫn trên một máy thì tính luôn là một người mà, như bạn @Qynklee đã bình luận.
