### ISSUE TITLE
[Góp ý] Thêm option chặn hiển thị đã xem trong group

### ISSUE THREAD

**Issue by valoteni** [J2TeaM/J2TeaM-Security#16]
Mình rất thích các tính năng của J2TeaM Security. Mình hay sử dụng các tính năng ẩn danh.
Nhưng mà mới đây hơi phiền 1 chút là hiển thị đã xem trong group. Lúc báo cái là có ib mấy người liền mà mình thì đang bận. Có khi sếp ib giục cũng hơi hốt :P 
Mong là sẽ có thêm option chặn đã xem trong group trong ver tới
Thank you!

**Comment by J2TEAM** [comment]
Ý bạn là chặn "đã xem" trong group chat?
