### ISSUE TITLE
Bộ đếm thời gian online Fb

### ISSUE THREAD

**Issue by TuNguyen01s** [J2TeaM/J2TeaM-Security#2]
Gửi Dev, mình đang sử dụng và nhận thấy rằng Clock này đếm thời gian có một chút vấn đề...tức là sau khi tắt trình duyệt khoảng 1h hoặc tắt máy đi, khi truy cập lại Fb thì vẫn tiếp tục đếm thời gian lúc tắt trình duyệt, hoặc bắt đầu đếm từ vài phút.....vì vậy nó chưa được chính xác.
- Về theme thì mình thấy có lỗi gì đó khi tải thêm bài viết ở FB. Dev có thể phát triển thêm việc tuỳ chỉnh css có sẵn để người dùng không biết về IT vẫn có thể tuỳ chỉnh theme theo ý muốn.
Cám ơn ! :)) Ứng dụng rất hay :+1:

**Comment by J2TeaM** [comment]
Chào bạn!

Về tính năng đếm thời gian hoạt động thì nó đếm thời gian bạn dùng Facebook trong cả một ngày và nó chỉ reset thời gian vào 24:00 thôi :grin: 

Bạn có thể chỉnh sửa CSS bằng tính năng Dark Theme Editor nhé: https://www.youtube.com/watch?v=Tc8k4r8NlAA

**Comment by TuNguyen01s** [comment]
ok Dev :+1:  :)
