### ISSUE TITLE
Bạn tạm thời bị hạn chế tạo hành động biểu đồ mở

### ISSUE THREAD

**Issue by dongloo** [J2TeaM/J2TeaM-Security#27]
Dear J2TeaM-Security,
Mình dùng extension J2TeaM-Security đã lâu, thì mình gặp phải cảnh báo của facebook và bị hạn chế tạo hành động biểu đồ mở trong thời gian là 1 ngày, liệu đây có phải là do dùng extension gây ra không, mình xin cảm ơn!

**Comment by J2TEAM** [comment]
Vấn đề này hoàn toàn không liên quan tới extension nhé. Mình cũng bị 1, 2 lần rồi.
