### ISSUE TITLE
Lỗi ẩn thời gian hoạt động

### ISSUE THREAD

**Issue by seiyashun** [J2TeaM/J2TeaM-Security#3]
Ad thử check dùm e chớ e để ý là e xài Ẩn thời gian hoạt động thì nếu ngkhác dùng máy tính thì sẽ không thấy được e online nhưng dùng điện thoại thì lại thấy e online  
![image](https://cloud.githubusercontent.com/assets/15777662/20108267/053719f4-a60e-11e6-861c-522039733d56.png)
![image](https://cloud.githubusercontent.com/assets/15777662/20108275/0b2117a2-a60e-11e6-8b65-09750b6c44b7.png)

**Comment by TuNguyen01s** [comment]
![image](https://cloud.githubusercontent.com/assets/23293332/20164962/cecab32e-a73b-11e6-9d28-7d8a471dbe56.png)
mình không thấy có chức năng "Ẩn thời gian hoạt động" nhỉ ?

**Comment by seiyashun** [comment]
Gõ juno là ra mà

Vào 10-11-2016 11:50, "TuNguyen01s" <notifications@github.com> đã viết:

**Comment by TuNguyen01s** [comment]
là sao bạn ?

**Comment by TuNguyen01s** [comment]
@seiyashun là sao bạn ?

**Comment by seiyashun** [comment]
Th gian hoạt động trên messager ấy , bạn bên tl mà bạn hỏi lại mình là s

Vào 10-11-2016 11:53, "TuNguyen01s" <notifications@github.com> đã viết:
