### ISSUE TITLE
Thống kê, xếp hạng Facebook

### ISSUE THREAD

**Issue by TuNguyen01s** [J2TeaM/J2TeaM-Security#6]
Giờ mới phát hiện ra là chức năng này chỉ áp dụng cho tài khoản Fb đăng nhập ở chế độ thường :))
,tức là ở chế độ "Ẩn danh" thì chỉ get info của tài khoản Fb đăng nhập ở chế độ thường...
- Dev có thể cải thiện nó không ? Cám ơn ạ.

**Comment by J2TeaM** [comment]
Do Chrome không cho can thiệp vào chế độ ẩn danh nên các công cụ mở từ Menu ngữ cảnh chỉ có thể mở ở chế độ thường nhé!
