### ISSUE TITLE
Bộ đếm thời gian Online facebook

### ISSUE THREAD

**Issue by Qynklee** [J2TeaM/J2TeaM-Security#9]
Bộ đếm thời gian Online facebook bị sai khi sử dụng nhiều Tab để truy cập Facebook, khi đó thời gian của các Tab sẽ khác nhau, mong Junookyo sớm xem xét .... 
Tks U phần mềm quá tốt 5start <3

**Comment by J2TEAM** [comment]
Mình đã giảm thời gian đồng bộ nên thời gian giữa nhiều tab sẽ chính xác hơn rồi nhé!
